---
- name: configure VLANs
  hosts: juniper arista
  gather_facts: false
  vars_files: 
    - vars/network-data.yml

  tasks:

  - name: ensure vlans state on Juniper routers
    junipernetworks.junos.vlans:
      state: deleted 
      config: "{{ vlans_juniper }}"
    when: ansible_network_os == 'junos'

  - name: ensure vlans state on Arista routers
    arista.eos.vlans:
      state: deleted 
      config: "{{ vlans_arista }}"
    when: ansible_network_os == 'eos'